#!/usr/bin/env bash
# Prepare clangd for this PlatformIO project.
#
# clangd has no Xtensa target and does not reuse the xtensa GCC driver's
# built-in search paths (that would require launching it with --query-driver),
# so two things are needed for editor diagnostics to be meaningful:
#
#   1. .pio/clangd-shim/machine/endian.h — the newlib header ESP-IDF's platform
#      headers include. It is generated here (never committed, never compiled
#      into the firmware) so clangd does not fall over at the first include.
#   2. a merged compile_commands.json containing both the firmware and the
#      native test environments, so clangd gets real include paths for test/
#      sources too.
#
# Re-run this after `pio pkg update` or when the toolchain changes.
set -euo pipefail

cd "$(dirname "$0")/.."

SHIM_DIR=.pio/clangd-shim/machine
mkdir -p "$SHIM_DIR"
cat > "$SHIM_DIR/endian.h" <<'EOF'
/* clangd-only shim (generated by tools/setup-clangd-shim.sh) - never compiled
 * into the firmware. Supplies the newlib <machine/endian.h> that ESP-IDF's
 * platform headers include, without pulling in the rest of newlib (which
 * conflicts with the host C/C++ headers clangd uses). Values are the standard
 * newlib byte-order macros for the little-endian ESP32-S3 (Xtensa LX7); the
 * real build uses newlib's own header. */
#ifndef __MACHINE_ENDIAN_H__
#define __MACHINE_ENDIAN_H__
#define _LITTLE_ENDIAN 1234
#define _BIG_ENDIAN 4321
#define _PDP_ENDIAN 3412
#define _BYTE_ORDER _LITTLE_ENDIAN
#define _QUAD_HIGHWORD 1
#define _QUAD_LOWWORD 0
#define LITTLE_ENDIAN _LITTLE_ENDIAN
#define BIG_ENDIAN _BIG_ENDIAN
#define PDP_ENDIAN _PDP_ENDIAN
#define BYTE_ORDER _BYTE_ORDER
#define __bswap16(x) __builtin_bswap16(x)
#define __bswap32(x) __builtin_bswap32(x)
#define __bswap64(x) __builtin_bswap64(x)
#define __htonl(x) __bswap32(x)
#define __htons(x) __bswap16(x)
#define __ntohl(x) __bswap32(x)
#define __ntohs(x) __bswap16(x)
#endif
EOF

# Firmware env first, then the native (test) env, then explicit host entries for
# the native test sources. PlatformIO's compiledb target never emits the test
# translation units, and without an entry clangd *infers* one from an unrelated
# libdeps file (xtensa flags), which makes host-targeted tests fail to parse.
pio run -e attak-iot-firmware -t compiledb >/dev/null
cp compile_commands.json compile_commands.firmware.json
pio run -e native -t compiledb >/dev/null
python3 - <<'PY'
import glob, json, os

project = os.getcwd()
firmware = json.load(open('compile_commands.firmware.json'))
native = json.load(open('compile_commands.json'))

seen, merged = set(), []
for entry in firmware + native:
    if entry['file'] in seen:
        continue
    seen.add(entry['file'])
    merged.append(entry)

test_flags = [
    'clang++', '-std=gnu++17', '-fsyntax-only',
    '-Isrc', '-Iinclude',
    '-I.pio/libdeps/native/Unity/src',
    '-I.pio/libdeps/native/ArduinoJson/src',
]
for path in sorted(glob.glob('test/*/*.cpp')):
    absolute = os.path.join(project, path)
    if absolute in seen:
        continue
    seen.add(absolute)
    merged.append({'directory': project, 'file': absolute, 'arguments': test_flags + [absolute]})

json.dump(merged, open('compile_commands.json', 'w'), indent=1)
print(f"compile_commands.json: {len(merged)} translation units")
PY
rm -f compile_commands.firmware.json
echo "clangd shim + compile database ready"
